name: more_loading_gif
description: A package to show loading gif as assets with transparent background.
version: 0.0.2
homepage: https://github.com/ajomuch92/more-loading-gif

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/


